// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for linux - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSOC4c-qTEV6hVCHjOL1baObS_B_wRng8',
    appId: '1:540952718446:web:65350d398b5cbcd6db8a7f',
    messagingSenderId: '540952718446',
    projectId: 'device-streaming-b7af43e8',
    authDomain: 'device-streaming-b7af43e8.firebaseapp.com',
    databaseURL: 'https://device-streaming-b7af43e8-default-rtdb.firebaseio.com',
    storageBucket: 'device-streaming-b7af43e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0VSbX7lmuJO80rYgaX1KUr6iejMbjOaY',
    appId: '1:540952718446:android:f3809446a6a57ffedb8a7f',
    messagingSenderId: '540952718446',
    projectId: 'device-streaming-b7af43e8',
    databaseURL: 'https://device-streaming-b7af43e8-default-rtdb.firebaseio.com',
    storageBucket: 'device-streaming-b7af43e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3gAcXLHFSxsU0scIqSXuRzLk3W6PUNx0',
    appId: '1:540952718446:ios:4dee7c23243d79dbdb8a7f',
    messagingSenderId: '540952718446',
    projectId: 'device-streaming-b7af43e8',
    databaseURL: 'https://device-streaming-b7af43e8-default-rtdb.firebaseio.com',
    storageBucket: 'device-streaming-b7af43e8.firebasestorage.app',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3gAcXLHFSxsU0scIqSXuRzLk3W6PUNx0',
    appId: '1:540952718446:ios:4dee7c23243d79dbdb8a7f',
    messagingSenderId: '540952718446',
    projectId: 'device-streaming-b7af43e8',
    databaseURL: 'https://device-streaming-b7af43e8-default-rtdb.firebaseio.com',
    storageBucket: 'device-streaming-b7af43e8.firebasestorage.app',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSOC4c-qTEV6hVCHjOL1baObS_B_wRng8',
    appId: '1:540952718446:web:88930138b3bd2bfddb8a7f',
    messagingSenderId: '540952718446',
    projectId: 'device-streaming-b7af43e8',
    authDomain: 'device-streaming-b7af43e8.firebaseapp.com',
    databaseURL: 'https://device-streaming-b7af43e8-default-rtdb.firebaseio.com',
    storageBucket: 'device-streaming-b7af43e8.firebasestorage.app',
  );

}